package com.sapient.publicis.nipa.ew.order.adapter.dynamodbupgraded;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.sapient.publicis.nipa.ew.order.util.DateTimeConverter;
import lombok.*;

import java.time.LocalDate;

/**
 * @Author Pawan
 */
@DynamoDBTable(tableName = "ew-orders")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode
public class ElectricVehicleBattery {

    @DynamoDBHashKey(attributeName = "ew_id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "vin")
    private String vin;

    @DynamoDBAttribute(attributeName = "order_status")
    private Boolean orderStatus = false;

    @DynamoDBAttribute(attributeName = "current_warranty_expiration_date")
    @DynamoDBTypeConverted(converter = DateTimeConverter.class)
    private LocalDate currentWarrantyExpirationDate;

    @DynamoDBAttribute(attributeName = "car_configuration")
    private String carConfiguration;

    @Builder
    public static ElectricVehicleBattery getInstance(String id, String vin, boolean orderStatus, LocalDate currentWarrantyExpirationDate, String carConfig) {
        return new ElectricVehicleBattery(id, vin, orderStatus, currentWarrantyExpirationDate, carConfig);
    }

    public ElectricVehicleBattery setId(String id){
        this.id = id;
        return this;
    }
}
